# Generated by Django 5.0.6 on 2024-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duedate',
            field=models.DateField(null=True, verbose_name='期限'),
        ),
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50, null=True, verbose_name='優先度'),
        ),
    ]
